server:
  port: 7001

spring:
  datasource:
    url: jdbc:mysql://10.211.55.4:3306/gmall_product?useSSL=false&allowPublicKeyRetrieval=true

    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml

app:
  minio:
    endpoint: http://10.211.55.4:9000
    accessKey: admin
    secretKey: admin123456
    bucketName: gmall
